[settings]
experimental = true

[tools]
node = "latest"
bun = "latest"
ruby = "3.4.8"
# hugo = "latest"
# zig = "latest"
# go = "latest"
# ruby = "latest"
# erlang = "latest"
# elixir = "latest"
# haskell = "9.12.2"
# ocaml = "latest"
# dotnet = "latest"
# java = "latest"
# nasm = "2.16"
# kotlin = "latest"
# scala = "latest"
# groovy = "latest"
# julia = "1.11.6"
